---
title: "Publications"
toc: true
toc-location: left
toc-title: "Sections"
---

*Notes: \* indicates first author; ^&dagger;^ indicates student first author*


## Journal Articles {#journal-articles}

- ^&dagger;^Pandey, A., J. Shragge, **A.J. Girard**, A. Kumar, (2026) "[Scholte-wave Adjoint Tomography for Building Low-frequency, Offshore Shear-wave Velocity Models](https://eartharxiv.org/repository/view/11759/)," *Geophysics*, in review. *Earth ArXiv*.

- ^&dagger;^Pandey, A., J. Shragge, **A.J. Girard**, (2025) "[First-order control factors for ocean-bottom ambient seismology interferometric observations](https://doi.org/10.1093/gji/ggaf351)," *Geophysical Journal International*, Volume 243, Issue 2.

- ^&dagger;^Pandey, A., S. de Ridder, J. Shragge, **A.J. Girard**, (2025) "[Ocean-bottom seismic interferometry in coupled acoustic-elastic media](https://academic.oup.com/gji/article/242/3/ggaf271/8203306)," *Geophysical Journal International*, Volume 242, Issue 3.

- \***Girard, A.J.**, J. Shragge, M. Danilouchkine, C. Udengaard, S. Gerritsen, (2024) "[Observations from the Seafloor: Ultra-low-frequency Ambient Ocean-Bottom Nodal Seismology at the Amendment Field](https://doi.org/10.1093/gji/ggae249)," *Geophysical Journal International*, Volume 239, Issue 1, Pages 17–36. [[EarthArXiv]](https://eartharxiv.org/repository/view/6769/)

- Shragge, J., **A.J. Girard**, C. Oren, R. Krahenbuhl (2024) "[Elastic Time-Reverse Imaging of Backscattered Surface-Wave Data](https://library.seg.org/doi/10.1190/geo2023-0569.1)," *GEOPHYSICS* 89: KS119-KS128.

- Nakata, R., N. Nakata, **A.J. Girard**, D. Lumley, M. Ichikawa, A. Kato, Z. Xue, (2024) "[Time-lapse velocity change estimation by anisotropic elastic full waveform inversion for CO₂ sequestration at the Nagaoka CCS site](https://www.sciencedirect.com/science/article/pii/S1750583624001191)," *International Journal of Greenhouse Gas Control* 136, 104176.

- ^&dagger;^Chambers, D., G. Jin, A. Tourei, A.H. Saeed Issah, A. Lellouch, E. Martin, D. Zhu, **A. Girard**, S. Yuan, T. Cullison, T. Snyder, S. Kim, N. Danes, N. Punithan, M.S. Boltz, and M.M. Mendoza, (2024) "[DASCore: a Python Library for Distributed Fiber Optic Sensing](https://seismica.library.mcgill.ca/article/view/1184)," *Seismica* 3(2).

- ^&dagger;^Yang, J., J. Shragge, **A.J. Girard**, E. Gonzalez, J. Ticona, A. Minaya and R. Krahenbuhl, (2023) "[Seismic Characterization of a Recent Majes Landslide Complex](https://www.mdpi.com/2071-1050/15/18/13574)," *Sustainability*, 15, no. 18: 13574.

- ^&dagger;^Pandey, A., J. Shragge, D. Chambers, and **A. Girard**, (2023) "[Developing a Distributed Acoustic Sensing Seismic Land Streamer: Concept and Validation](https://library.seg.org/doi/10.1190/geo2023-0072.1)," *GEOPHYSICS*, 88: WC59-WC67.

- \***Girard, A.J.**, Shragge, J. and Olofsson, B., (2023) "[Low-frequency ambient ocean-bottom node surface-wave seismology: A Gulf of Mexico case history](https://library.seg.org/doi/10.1190/geo2021-0732.1)," *GEOPHYSICS* 88: B21-B32. [[Kudos]](https://link.growkudos.com/1hoqhvc5nuo)

- \***Girard, A.J.** and Shragge, J. (2020) "[Automated processing strategies for ambient seismic data](https://onlinelibrary.wiley.com/doi/10.1111/1365-2478.12794)," *Geophysical Prospecting*, 68: 293-312.

- \***Girard, A.J.** and Shragge, J. (2020) "[Direct migration of ambient seismic data](https://onlinelibrary.wiley.com/doi/10.1111/1365-2478.12792)," *Geophysical Prospecting*, 68: 270-292.

- \***Girard, A.J.** (2019) "[Automated processing and direct migration of ambient seismic data](https://research-repository.uwa.edu.au/en/publications/automated-processing-and-direct-migration-of-ambient-seismic-data)," *University of Western Australia*, PhD Thesis.

## Conference Abstracts {#conference-abstracts}

### 2025

- Roecker, S., N. Bennington, R. Denlinger, A. Flinders, **A. Girard**, M. Haney, R. Kramer, G. Lin, D. O'Connell, C. Ruggles and E. Vinarski (2025), "[Refined images of the plumbing system beneath the Kīlauea Summit based on the analysis of active and passive seismic data in conjunction with gravity disturbance observations](https://agu.confex.com/agu/agu25/meetingapp.cgi/Paper/1899392)," *AGU Fall Meeting 2025*.

- Martin, E.R., D. Chambers, G. Jin, A. Tourei, A.H. Issah, A. Lellouch, S. Yuan, **A.J. Girard**, D. Zhu, T. Cullison, N. Punithan, T. Snyder, S. Kim, N. Danes, S. Boltz, M. Mendoza, P. Li and Y. Song (2025), "[Distributed Acoustic Sensing Data Analysis Ecosystem: DASCore and related Python packages](https://agu.confex.com/agu/agu25/meetingapp.cgi/Paper/1893955)," *AGU Fall Meeting 2025*.

- ^&dagger;^Pandey, A., J.C. Shragge and **A.J. Girard** (2025), "[First-order Control Factors for Ocean-bottom Ambient Seismology Interferometric Observations](https://imageevent.aapg.org/portals/26/abstracts/2025/4303580.pdf)," *IMAGE, SEG Annual Meeting*, Houston, Texas.

- ^&dagger;^Davis, D., J.C. Shragge, **A.J. Girard** and S. de Ridder (2025), "[Ambient seismic frequency-domain gradiometry](https://imageevent.aapg.org/portals/26/abstracts/2025/4316565.pdf)," *IMAGE, SEG Annual Meeting*, Houston, Texas.

- ^&dagger;^Pels, M., J.C. Shragge and **A.J. Girard** (2025), "[3-D elastic time-reverse imaging of a void anomaly: A case history](https://imageevent.aapg.org/portals/26/abstracts/2025/4310907.pdf)," *IMAGE, SEG Annual Meeting*, Houston, Texas.

### 2024

- \***Girard, A.J.**, D. O'Connell, J. Shragge, and M.M. Haney (2024), "[Active-source tomography velocity modelling of the Kīlauea summit and surrounding area](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1633763)," *AGU Fall Meeting 2024*.

- ^&dagger;^Tourei, A., D.J.A. Chambers, G. Jin, A.H. Issah, A. Lellouch, E. Martin, **A.J. Girard**, D. Zhu, S. Yuan, N. Punithan, T. Snyder, N. Danes, S. Boltz, and M. Mendoza (2024), "[DASCore: An open-source Python library for distributed acoustic sensing](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1653065)," *AGU Fall Meeting 2024*.

- Nakata, R., N. Nakata, **A.J. Girard**, D.E. Lumley, M. Ichikawa, A. Kato, and Z. Xue (2024), "[Time-lapse velocity change monitoring by anisotropic elastic full waveform inversion for CO₂ sequestration at the Nagaoka CCS site](https://agu.confex.com/agu/agu24/meetingapp.cgi/Paper/1760108)," *AGU Fall Meeting 2024*.

- \***Girard, A.J.**, J. Shragge, M. Danilouchkine, C. Udengaard, S. Gerritsen (2024), "[(Ultra-)low frequency interferometric surface-wave scattering in ambient OBN seismic data](https://drive.google.com/file/d/1DEH9TXrBQlmjBgtOM5H2VFOGpixSFzAD/view?usp=drive_link)," *IMAGE, SEG Annual Meeting*, Houston, Texas.

- ^&dagger;^Pandey, A., J. Shragge, and **A.J. Girard** (2024), "Ambient crosscorrelation modeling for dense ocean-bottom node arrays: a Gulf of Mexico example," *IMAGE, SEG Annual Meeting*, Houston, Texas.

- J. Shragge and **A. Girard** (2024), "Observations From the Seafloor: Ultra-Low-Frequency Ambient Ocean-Bottom Nodal Seismology From the Gulf of Mexico," *SSA 2024 Annual Meeting*.

- ^&dagger;^D. Chambers, G. Jin, A. Tourei, A.H.S. Issah, A. Lellouch, E. Martin, D. Zhu, **A. Girard**, S. Yuan, T. Cullison, T. Snyder, S. Kim, N. Danes, N. Punithan, S. Boltz, and M.M. Mendoza (2024), "DASCore: A python library for distributed acoustic sensing," *SSA 2024 Annual Meeting*.

### 2022

- Nakata, R., N. Nakata, **A. Girard**, M. Ichikawa, A. Kato, D. Lumley and Z. Xue (2022), "[Time-lapse crosswell seismic monitoring of CO₂ injection at the Nagaoka CCS site using elastic full waveform inversion](https://library.seg.org/doi/10.1190/image2022-3744414.1)," *SEG Technical Program Expanded Abstracts*: 802-806.

### 2021

- \***Girard, A.J.**, J. Shragge, and B. Olofsson (2021), "[Identifying salt flanks using low-frequency ambient OBN surface-wave seismology](https://library.seg.org/doi/abs/10.1190/segam2021-3592980.1)," *SEG Technical Program Expanded Abstracts*: 1991-1995. **[Honorable Mention for Best Paper](https://wiki.seg.org/wiki/Honorable_Mentions_%28Best_Paper,_Annual_Meeting%29)**

### 2017

- \***Girard, A.J.** and J. Shragge (2017), "[Automated Processing Workflow for Ambient Seismic Recordings](https://agu.confex.com/agu/fm17/meetingapp.cgi/Paper/263021)," *AGU Fall Meeting*, New Orleans, LA.

### 2016

- \***Girard, A.J.** and Shragge, J. (2016), "[Extracting body waves from ambient seismic recordings](https://library.seg.org/doi/10.1190/segam2016-13948136.1)," *SEG Technical Program Expanded Abstracts*: 2715-2719.

### 2015

- \***Girard, A.J.** and J. Shragge (2015), "[The utility of extended images in ambient seismic wavefield migration](https://agu.confex.com/agu/fm15/meetingapp.cgi/Paper/63197)," *AGU Fall Meeting*, San Francisco, CA.

### 2014

- Elapavuluri, P.K., and **Girard, A.J.** (2014), "[Estimating Seismic Uncertainity in Model Space](https://www.earthdoc.org/content/papers/10.3997/2214-4609.20141194)," *76th EAGE Conference and Exhibition*, p.1-5.

### 2010

- \***Girard, A.**, and Vasconcelos, I. (2010), "[Image‐domain time‐lapse inversion with extended images](https://library.seg.org/doi/abs/10.1190/1.3513744)," *SEG Technical Program Expanded Abstracts*: 4200-4204.

- \***Girard, A.**, Jie-A-Looi, M., Bakker, J., and Momot, F. (2010), "[Searching for a Roman Villa and Prehistoric Flint Mines in Kanton Zürich](https://drive.google.com/file/d/12ztUlNjx1vpwujxC8rIWE9Mac1EEnSSOy8TsKevVzjebNQxyQ19KHaR2g0b1/view?usp=sharing)," *1st Annual International Geoscience Student Conference*, Bucharest, Romania.

## Government Reports {#government-reports}

1. Shragge, J., **A. Girard**, H. Flamme, B. Artman, R. Krahenbuhl, J. Bradford, A. Kumar, P. Reppert, R. Hammack, and D. Glaser (2023), "[NETL Plastic Pipes Project – Final Report](https://www.osti.gov/servlets/purl/2202764)," DOE/NETL-2023/4327; NETL Technical Report Series; U.S. Department of Energy, National Energy Technology Laboratory: Pittsburgh, PA.

2. Shragge, J., **A. Girard**, H. Flamme, B. Artman, R. Krahenbuhl, J. Bradford, Y. Li, P. Reppert, R. Hammack, and D. Glaser (2023), "[NETL Plastic Pipes Project - June 2022 Progress Report](https://www.osti.gov/biblio/1924455)," United States.

## Non-Technical {#non-technical}

1. Ore, T., E.R. Martin, I. Rubio-Cisneros, **A. Girard**, J. Ma, S. Kanakiya, O. Sanuade, A. Titov, and R. de Souza (2023), "[Research Committee Update: Hot topics in geophysics: Progress, trends, and perspectives](https://library.seg.org/doi/10.1190/tle42050360.1)," *The Leading Edge* 42: 360–363.

2. Titov, A., **Girard, A.** and Martin, E. (2021), "[Research Committee Update: Working with - and for - early-career researchers](https://library.seg.org/doi/epub/10.1190/tle40060464.1)," *The Leading Edge* 40: 464.

3. \***Girard, A.** (2020), "[Student Zone: Students encouraged to build new regional Challenge Bowls](https://library.seg.org/doi/full/10.1190/tle39080600.1)," *The Leading Edge* 39: 600.

4. \***Girard, A.** (2010), "[Geophysics: Oh, the places a student can go! one student's journey](https://library.seg.org/doi/epdf/10.1190/tle29050604.1)," *The Leading Edge* 29: 604-605.
